import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GiElectric } from "react-icons/gi";
import { useEffect } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push("/login");
  }, []);
  return (
    <div>
      <Head>
        <title>KSEB | Billing System</title>
        <meta name="description" content="Generated by KSEB | Billing System" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center min-h-screen">
        <div className="flex mb-8 flex-row  items-center">
          <GiElectric color="#2979ff" size={35} />
          <h1 className="text-3xl primary-color font-semibold">
            Kerala State Electricity Board
          </h1>
        </div>
      </main>
    </div>
  );
}
