import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex p-20 items-center justify-center">
          <div className="box p-10 w-2/6 flex flex-col  items-center font-white  bg-white rounded-md">
            <h2 className=" text-3xl text-gray-800 font-medium">Admin Login</h2>
            <p className="text text-lg">Lorem ipsum consectetur</p>
            <div className="flex mt-4  w-full flex-col">
              <p className="text text-lg font-medium">User Name</p>
              <input
                type="text"
                className="input-box mt-1  outline-none p-2 rounded-sm"
                placeholder="Username"
              />
            </div>
            <div className="flex mt-4  w-full flex-col">
              <p className="text text-lg font-medium">Password</p>
              <input
                type="password"
                className="input-box mt-1 outline-none p-2 rounded-sm"
                placeholder="Username"
              />
            </div>
            <p className="text-red-500 mt-5 text-lg ">error text!</p>
            <button className="text-xl p-2 text-white font-medium bg-blue-400 dark-blue w-full mt-5">
              Login Now
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
