import Head from "next/head";
import Image from "next/image";
import { GiElectric } from "react-icons/gi";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex p-20 flex-col items-center justify-center">
          {" "}
          <div className="flex mb-8 flex-row  items-center">
            <GiElectric color="#2979ff" size={35} />
            <h1 className="text-3xl primary-color font-semibold">
              Kerala State Electricity Board
            </h1>
          </div>
          <div className="box p-10 w-2/6 flex flex-col  items-center font-white  bg-white rounded-md">
            <h2 className=" text-3xl text-gray-800 font-medium">Admin Login</h2>

            <div className="flex mt-4  w-full flex-col">
              <p className="text text-lg font-medium">User Name</p>
              <input
                type="text"
                className="input-box mt-1  outline-none p-2 rounded-sm"
                placeholder="Username"
              />
            </div>
            <div className="flex mt-4  w-full flex-col">
              <p className="text text-lg font-medium">Password</p>
              <input
                type="password"
                className="input-box mt-1 outline-none p-2 rounded-sm"
                placeholder="Username"
              />
            </div>
            <p className="text-red-500 mt-5 text-lg ">error text!</p>
            <button className="text-xl rounded-sm p-2 text-white font-medium bg-blue-400 dark-blue w-full mt-1">
              Login Now
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
